import type { Metadata } from "next";
import { Pirata_One } from "next/font/google";

import "./globals.css";

const pirataOne = Pirata_One({
  subsets: ["latin"],
  weight: "400", 
  variable: "--font-pirata", 
});


export const metadata: Metadata = {
  title: "A La Diablo Hot Sauce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pirataOne.variable} font-sans antialiased `}
      >
         
        {children}
      </body>
    </html>
  );
}
